### ISSUE TITLE
Not able to use `tab` helper

### ISSUE THREAD

**Issue by Jeyffrey** [emberjs/ember-test-helpers#1243]
Hello, I need some help !
When I do:
`import helpers from '@ember/test-helpers';`

In the `helpers` object, I don't have the [`tab` util](https://github.com/emberjs/ember-test-helpers/blob/master/addon-test-support/%40ember/test-helpers/dom/tab.ts).
I already tried with the latest version.

Is it normal? Should I do something specific?

**Comment by ro0gr** [comment]
have you tried named import:
```
import { tab } from '@ember/test-helpers';
```
?

**Comment by Jeyffrey** [comment]
> have you tried named import:
> 
> ```
> import { tab } from '@ember/test-helpers';
> ```
> 
> ?

Yeah I also tried it

**Comment by ro0gr** [comment]
May you provide with a minimal reproduction? otherwise it'd be impossible to reason about the issue.

**Comment by Jeyffrey** [comment]
We added a trap-focus to a modal component with a modifier, and we wanted to test it.
Here is the current branch https://github.com/1024pix/pix-ui/compare/dev...pix-5157-add-trap-focus.

Currently, in the project, the `@ember/test-helpers` version is 2.6.0, but I tried locally with the last one.
So, after updating it, I tried to import the `tab` util, but I wasn't able to. Whereas, I have no trouble with the `tap` one, for example.

**Comment by yannbertrand** [comment]
Hello @ro0gr,

We've set up [a minimal reproduction case](https://github.com/yannbertrand/ember-test-helpers-tab-reproduction).

The GitHub Action CI should fail because of the issue we have.

You can also run it locally with:
1. Cloning the repo
2. `npm ci` (we're using Node 16.14.0)
3. `npm test` or `npm start` then going to http://localhost:4200/tests

The simple test we have is in the [/tests/unit/components/trap-focus-test.js](https://github.com/yannbertrand/ember-test-helpers-tab-reproduction/blob/main/tests/unit/components/trap-focus-test.js) file. As you can see there, `tap` is imported and is a function but `tab` is not for some reason.

There is a warning because Ember CLI is not tested in our Node version because we're using the Ember 3.18.0 (the same issues occur with Ember 3.27.0) but we guessed it shouldn't cause this particular issue. (Our apps are slowly migrating to Ember 4).

Let us know if we can give you more informations.

Thanks by advance!

**Comment by yannbertrand** [comment]
Can confirm it works now, see https://github.com/yannbertrand/ember-test-helpers-tab-reproduction/actions/runs/10476962930/job/29017029938.

Thanks!
