### ISSUE TITLE
Tests fail after upgrading to 0.5.17 - unable to find custom store

### ISSUE THREAD

**Issue by toddjordan** [emberjs/ember-test-helpers#130]
My team uses a extended store object that gets resolved by Ember at runtime because we put the file in `services/store.js`.  Starting in the new release, our unit tests can't resolve our custom store, the unit test's resolver just gives us the ember one.  How do I load my custom store object from a unit test?  

As a workaround, I'm just going to refactor the test into an integration test, which does use the integrated store, but as a patch version upgrade, I wouldn't think I would be forced to do so...

**Comment by rwjblue** [comment]
@toddjordan - Is this a unit test?  If so, is `needs: ['service:store']` in place?

**Comment by rwjblue** [comment]
This is mostly a guess, but I believe this is because of the change that @nickiaconis and I did in #127.

Prior to that change, anything used/looked up during the initial registry setup would have been able to use the normal resolving process.  This means that when we call `DS._setupContainer` [here](https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/build-registry.js#L104), Ember Data was still able to use the resolver to get the "real" `service:store`.

After the change, the registry passed to `DS._setupContainer` does not have a valid resolver attached to it, and therefore Ember Data's setup process is not able to find the custom store.

**Comment by toddjordan** [comment]
Yeah, the needs was in place, but was loading the default store

**Comment by rwjblue** [comment]
@toddjordan - Gotcha, thanks.  I'm trying to come up with a fix, shouldn't be long.

**Comment by toddjordan** [comment]
thanks!

**Comment by Turbo87** [comment]
@rwjblue @toddjordan is this issue still relevant?

**Comment by rwjblue** [comment]
I believe this was already addressed, happy to reopen if I'm incorrect...
