### ISSUE TITLE
Anomalies in current published version compared to previous versions

### ISSUE THREAD

**Issue by MelSumner** [emberjs/ember-test-helpers#1402]
Screenshot: 
![CleanShot 2023-06-01 at 17 49 28@2x](https://github.com/emberjs/ember-test-helpers/assets/4587451/1dc4575b-3925-471a-aa7c-d737400f8f6a)
On the left, the files in `v2.9.3` in an app. On the right, the files in `v3.0.2` in an app. 

While the `types/` directory is now excluded intentionally, I suspect that the changelog and licenses still need to be published. We also really should not have had to change `public-types` to `dist-types` in order for it to successfully publish from a functional perspective. So something really weird is going on, and it needs deeper investigation.

**Comment by MelSumner** [comment]
So in considering what's changed between the two versions, the file structure is the first thing that comes to mind. 

I think we need to move the licenses inside of the addon folder. 
But if this was the complete answer, the CHANGELOG should have been published, so there's still something off.

**Comment by fivetanley** [comment]
Adding to the list of anomalies: It seems that only typescript files are ending up in the tarball published to npm. https://www.npmjs.com/package/@ember/test-helpers?activeTab=code. For version 3.0.2:

<img width="890" alt="Screenshot 2023-06-08 at 15 56 39" src="https://github.com/emberjs/ember-test-helpers/assets/1275021/d91c3cf9-3481-48f9-9252-9f97b32269cb">

This should be full of JS files but it's not. I think that's what's causing the build to fail for this PR (https://github.com/emberjs/ember-qunit/pull/1077). The app tries to pull in the add-on, which works, but because there are no JS files, and there is no `ember-cli-typescript` configured, no modules for `@ember/test-helpers` get built/defined, leading to the "no module @ember/test-helpers" error.

**Comment by NullVoxPopuli** [comment]
what's goofy is that the `prepack` script includes `build`, which generates all the JS
![image](https://github.com/emberjs/ember-test-helpers/assets/199018/14d538d6-801b-4555-8f32-aa7588e6da36)

But I confirmed that both `npm pack` and `yarn pack`, that all the JS files are excluded

**Comment by NullVoxPopuli** [comment]
I have a fix! https://github.com/emberjs/ember-test-helpers/pull/1408

**Comment by MelSumner** [comment]
Re-opening because `npm pack` is still revealing that we're missing changelog and license files. I think I know how to fix this, PR incoming.
