### ISSUE TITLE
moduleForModel doesn't play nicely with application serializer.

### ISSUE THREAD

**Issue by nathanhammond** [emberjs/ember-test-helpers#165]
Original report here: https://github.com/ember-cli/ember-cli/issues/4879

/cc @dustinfarris @stefanpenner

**Comment by oligriffiths** [comment]
Hey @nathanhammond what's the state of play with this. I'm getting that error when implementing an application serlializer test in 2.7.0 😞

**Comment by nathanhammond** [comment]
@oligriffiths It's still an open issue, we've tracked it down to [this file](https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/test-module-for-model.js), but nobody has investigated how to make it work.

Would you be willing to take a swing at it?

**Comment by jangxyz** [comment]
I just bumped into this. I'm now sure if this is the right way, but let me introduce the way I figured.

## Why fail

1. I generated an `ApplicationSerializer` to make a custom action (typical `keyForAttribute` override). ember-cli created a test for me at: `tests/unit/serializers/application-test.js`. 

  <small>At this time I already had another model `minute`, but I just wanted to make some default behavior. I have my own serializer for the that as well, along with the test.</small>

2. Serializer tests start with `moduleForModel`.
  - ```moduleForModel('application', 'Unit | Serializer | application', { })```
  - Under the hood, `moduleForModel` passes `TestModuleForModel`([ember-qunit/module-for-model.js](https://github.com/emberjs/ember-qunit/blob/v0.4.22/lib/ember-qunit/module-for-model.js#L5)),
     which registers the `setupModel` method that binds `this.subject` method that creates a model record, during the setup. ([ember-test-helpers/test-module-for-model.js](https://github.com/emberjs/ember-test-helpers/blob/v0.5.34/lib/ember-test-helpers/test-module-for-model.js#L8))

3. As `"application"` is passed in to `moduleForModel`, `TestModuleForModel` tries to find a model with such name, but fails. Hence **error**.

        TypeError: Attempting to register an unknown factory: `model:application`


## How I solved it

For my use case,  since I already have a separate model, all I need to do was pass the name of that model. I just patched `TestModuleForModel` class to read an optional `modelName` from the callbacks parameter -- it seemed like where you pass options.

```javascript
import { TestModule } from 'ember-test-helpers';

const TestModuleForModelWithName = TestModule.extend({
  init: function(modelName, description, callbacks) {
    this.modelName = callbacks.modelName || modelName; // CHECK FOR callbacks.modelName FIRST

    this._super.call(this, 'model:' + this.modelName, description, callbacks);

    this.setupSteps.push(this.setupModel);
  },
  // ...
});
```

Since I couldn't use the default `moduleForModel` function, I just directly called `createModule` in my test.

```javascript
import { createModule } from 'ember-qunit/qunit-module';

createModule(TestModuleForModelWithName, 'application', 'Unit | Serializer | application', {
  // Specify the other units that are required for this test.
  needs: ['serializer:application'],
  modelName: 'minute',
});

```

## In general

However I can't think of a way to let ember-cli generate a *sane test* that passes by default, because it can't figure out which model to use when you create an application serializer.
It would be nice for the default `TestModuleForModel` class to accept `modelName` option like the patch though, so people could easily get it figured.

Maybe generating the `modelName` option with a comment will help others to figure it out?


What do you think?

**Comment by nathanhammond** [comment]
@jangxyz This is a unique situation and we can likely write one-off code to support it. Is that something that you would be willing to undertake and write a PR for?

**Comment by skarger** [comment]
I just had this problem with circumstances similar to what @jangxyz described above.

```
$ ember version
ember-cli: 2.13.2
```

I solved it by running `ember generate model application`. 
Then the auto-generated `tests/unit/serializers/application-test.js` passes as-is, specifically this line:
`moduleForModel('application', 'Unit | Serializer | application', {`

It seems vaguely wrong to generate an extraneous model but it was a simple fix.

**Comment by rwjblue** [comment]
This should be addressed when using the new testing APIs provided by ember-qunit (e.g. `moduleForModel` is no longer "a thing").

Closing....
