### ISSUE TITLE
Expose `element` in component integration tests

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember-test-helpers#184]
see https://github.com/emberjs/ember.js/issues/14630

/cc @locks @rwjblue

**Comment by Turbo87** [comment]
Note that this is already exposed as the private `_element` property (see https://github.com/emberjs/ember-test-helpers/pull/172), but should be renamed to `element` to make it public API.

**Comment by les2** [comment]
@Turbo87 would it be necessary (or possible) to create a "deprecating alias" for the old property / maintain backwards compatibility?

my thoughts are that it's not required to maintain back compat because it is private.

*but* would any important downstream users be broken by renaming this property?

**Comment by rwjblue** [comment]
I'd prefer to preserve compat if possible.  Seems like we can use `Object.defineProperty` getters or simply save the same element to `this.element` or `this._element`...

**Comment by rwjblue** [comment]
Closed by https://github.com/emberjs/ember-test-helpers/pull/220.
