### ISSUE TITLE
Update `triggerKeyEvent` to handle `code` and `key`.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember-test-helpers#265]
From https://github.com/emberjs/ember-test-helpers/pull/258#discussion_r155963086:

> When I initially copied `keyEvent`, I continued to use `keyCode` as the main way to set the key, but it seems to be [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) and the new alternatives are [KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) and [KeyboardEvent.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key), specially the last one.
>
> Perhaps we might want to start using it, or maybe assume that integers mean `keyCode` and strings mean `key`.

**Comment by pixelhandler** [comment]
Yes, we should use `key`, here is an example https://github.com/q2ebanking/ember-unified-select/blob/master/addon/components/select-box.js#L108 it is so much nicer, refactoring that code from `keyCode` was a so nice. 

- looking forward to helpers using `key` as well, https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key

**Comment by cibernox** [comment]
@pixelhandler @rwjblue I've started a PR to fix `triggerKeyEvent`. At the moment it is broken in one ways and could be improved in one.

1. **Broken:** `triggerKeyEvent(selector, 'keydown', 13)` fires a even in which `e.keyCode === 13` and `e.key === 13`. [`KeyboardEvent#key`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) is supposed to be a string. In the case above it's value should have been `"Enter"`. I've created a mapping from numbers to strings to generate more realistic events.
2. **Improvement**. Given that `keyCode` is deprecated and `key` is the recommended approach, I believe that calls of the form `triggerKeyEvent(selector, 'keydown', 'Tab')` should also be valid invocations. I'm improving the helper to assume that when receiving a number it must guess the `key` from it, and when receiving a string it assumes it's receiving the key and figures out the keycode.

I'll try to have it ready tomorrow.

**Comment by StephenAWalsh** [comment]
FYI this broke a few tests for us and never received a deprecation warning before hard failure after new npm install.

`await triggerKeyEvent(SELECTOR, 'keydown', 13);` had to be changed to `await triggerKeyEvent(SELECTOR, 'keydown', 'enter');`

Should the former still work?  Should I have seen deprecation warnings on these tests?

**Comment by cibernox** [comment]
That sounds legit code and I'd expect it to work. 

But more importantly I don't see how this could be working before as `event.key` used to be the number 13 before my PR 🤔 (which was entirely wrong as event.key must be a string)

**Comment by StephenAWalsh** [comment]
The event object has these keys using the 'enter' string:
```
key:"enter"
keyCode:NaN
```
and the object has the following with the number 13:
```
key:"Enter"
keyCode:13
```

**Note the capitalization difference.**  But IDK why it was working previously, since as you say it shouldn't have.  We migrated this test code away from JQuery just under a month ago and it's been working fine since using the number 13.  Turns out before we were triggering a jQuery keyDown event without a key object and this test wasn't even working properly before I ran the below codemod and manually fixed this test.

We used to use `this.$(SELECTOR).val('Boo').trigger('keydown');`

https://github.com/simonihmig/ember-test-helpers-codemod is where I got the idea to use a numbered key code.

**Comment by cibernox** [comment]
just to clarify `triggerKeyEvent(SELECTOR, 'keydown', 13)` and `triggerKeyEvent(SELECTOR, 'keydown', 'Enter');` should be equivalent. The key events are capitalized, so `enter` is not a valid value.

But on your original message you mentioned that `triggerKeyEvent(SELECTOR, 'keydown', 13)` stopped working with the last update, and that is surprising as the `key:"Enter", keyCode:13` you report seems correct.

**Comment by StephenAWalsh** [comment]
OK, so turns out we did not want to trigger an 'Enter' key here, just a keydown event.  Now I pass 'space' in, because I really want to be hitting the default case of my switch statement.

Your change actually 'fixed' `'keydown', 13`.

My mistake.  Took me a while to sort this out.

Seems there is no way to trigger just a keydown event, whereas you can with jQuery, which is why I'm just passing 'space' as the argument instead of 13 or 'enter'.

**Comment by cibernox** [comment]
Yes, that makes sense then. Before my PR, `e.key` was essentially broken. And yes, with the new testing it's impossible to send a key event without key, and I think it's a good thing because it's impossible to the user to press a key without a `keyCode`/`key`.

I've created https://github.com/emberjs/ember-test-helpers/issues/368 to add a warning/error when the `key` string is invalid, like `enter`.

You mentioned you are passing `"space"`, which is also an invalid `key` value. The `key` of the spacebar key is `""` (empty string).

**Comment by istateside** [comment]
Sorry to resurrect an old issue, but was the `code` property intentionally left out of the fix here? I've got a failing test because we're using a keyboard shortcut that relies on the `code` property. I had skipped the test and added a comment linking to this issue, thinking that it would eventually be fixed. We can refactor to use something else, but is there a reason why `code` was not implemented?

From my understanding, `key` and `code` are both supported for different reasons- `key` gives you the string 'value' of a keypress, whereas `code` is useful for telling which physical button was pressed, regardless of keyboard layout or language.

**Comment by gossi** [comment]
Same here, `code` isn't set. I would suggest, to change the 4th param from modifiers to props. That said, this code works:

```
await triggerKeyEvent('[data-test-code-input-1]', 'keydown', 'Digit4', {code: 'Digit4'});
```

Also will provide squiggly red lines if you are using TS. May I suggest this API:

```
triggerKeyEvent(target: Target, eventType: KeyboardEventType, key: number | string, modifiers: KeyModifiers = DEFAULT_MODIFIERS);
triggerKeyEvent(target: Target, eventType: KeyboardEventType, key: number | string | Props);
```

where `Props` is everything the `KeyboardEvent` will take. This way it is BC but will provide the flexibility we have to deal with when handling key events.
