### ISSUE TITLE
this.element is not accessible until this.render() is settled

### ISSUE THREAD

**Issue by ro0gr** [emberjs/ember-test-helpers#281]
I try to test if the loading animation is rendered while the component is loading data.

The test looks something like:
```js
import { module, test } from 'qunit';
import { setupRenderingTest } from 'ember-qunit';
import { waitFor } from '@ember/test-helpers';
import hbs from 'htmlbars-inline-precompile';

module('Integration | Component | my-component', function(hooks) {
  setupRenderingTest(hooks);

  test('it renders spinner', async function(assert) {
    // Do not use `await` intentionally. 
    // Otherwise it waits until ajax request is finished 
    // which prevents me to test loader existence
    this.render(hbs`{{my-component
      itemId="1"
    }}`);

    await waitFor('.loading-box');

    assert.ok(1);
  });
});
```

When test execution reaches `waitFor` I get the following error:
> Must setup rendering context before attempting to interact with elements.

As far as I can see element is set only after rendering is complete:

https://github.com/emberjs/ember-test-helpers/blob/b0f037b7361388f051d0f32615fdedd2581ff4bf/addon-test-support/%40ember/test-helpers/setup-rendering-context.js#L139-L146

The first thing came into my mind is to move setting of element in the very beginning of rendering cause seems like it always points to the same container _'#ember-testing > .ember-view'_. However the comment regarding ember <= 2.4 makes me think it might be not the right solution.

**Comment by rwjblue** [comment]
This came up in slack (`#dev-testing`) the other day. I definitely agree that this is a case that we want to support, and that your test looks about like what I'd expect to be able to write.

> The first thing came into my mind is to move setting of element in the very beginning of rendering cause seems like it always points to the same container '#ember-testing > .ember-view'.

The issue here is that the first `.ember-view` is created lazily, so we can't eagerly set it up the way things are structured at the moment.

I was thinking that now `setupRenderingTest` is much more explicit around needing to render (whereas `moduleForComponent('...', { integration: true })` was quite useful even unrelated to rendering), that we can actually move work around a bit so that the `setupRenderingContext` call itself creates the root element. 

I'm working up a possible solution...
