### ISSUE TITLE
Unit testing components with new attrs hash

### ISSUE THREAD

**Issue by amk221** [emberjs/ember-test-helpers#63]
Upgrade path to using the new `attrs` hash is difficult...
1. For a unit test which calls `this.render`:
   The component lifecycle hooks don't get called as you would expect.
2. For a unit test which _doesn't_ call `this.render`:
   You still need to be able to get the component's attributes, but you can't, because `didInitAttrs` hasn't been called. 
   (A potential workaround is to manually call `didInitAttrs` but this only works if you actually have a function called `didInitAttrs`)

Apologies if this is the wrong repo.

**Comment by mmahalwy** [comment]
I am experiencing this too. Any luck?

**Comment by amk221** [comment]
Life is better using component integration tests, but I still think this is an issue

**Comment by mmahalwy** [comment]
Yeah, I need to switch our tests to integration tests...

**Comment by bendemboski** [comment]
I definitely think this is worth addressing. Integration tests and unit tests are different things, and unit tests not actually simulating the running conditions of components is problematic.

Unit tests are great for white-box testing components -- trigger an action or set a property, and make sure that a computed property updated properly, or that another action was triggered or something. For the same reason that you don't always want to test your application by interacting only with the DOM (i.e. acceptance tests), you don't always want to test your components by interacting only with the DOM (i.e. integration tests). In both cases you sometimes was unit tests.

So why not just write unit tests as integration tests? Well, you can't without some serious hackery because integration tests don't give you access to the component object (```this.subject()``` isn't implemented). But now if you write unit tests, the choice is between making sure that they don't depend on any of the lifecycle hooks or, worse yet, on the attrs hash, or you have to mock that all up yourself :(

**Comment by rwjblue** [comment]
I believe that this should work properly now with the new ember-qunit APIs. Happy to reopen if I am mistaken...
