### ISSUE TITLE
Inject integration test helpers into component integration tests.

### ISSUE THREAD

**Issue by tim-evans** [emberjs/ember-test-helpers#67]
I found myself using the helpers `click`, `keyDown`, and friends in component integration tests. This worked for me because our `test-helpers.js` starts a test on every QUnit run:

``` javascript
import startApp from './helpers/start-app';

QUnit.testStart(function () {
  window.App = startApp();
});
```

Using test helpers in component tests where `integration: true` feels very natural. Any thoughts on injecting test helpers in the setup for the `moduleForComponent`?

**Comment by mitchlloyd** [comment]
I was trying to put together a test for a component that makes an ajax call and found it very awkward. Being able to use these test helpers that would be very helpful.

**Comment by praxxis** [comment]
This worked out of the box for me in 1.12, but in one of the point release 1.13's it broke, due to [this change](https://github.com/emberjs/ember.js/commit/456fdcbed7e407c35d957d4fa31e4f9a2ecd076d). Basically, view lookups stopped being a just-in-time check of a global shared by all "applications" (I put that in quotes because technically there's no application in the test helpers, but views do get registered into that global). That change meant that the application built by `startApp` no longer had knowledge of the component views created in the test. When an event was invoked in the component, by clicking or filling in or whatever, the application event dispatcher couldn't find the view with the action corresponding to the event.

I fixed this by creating a test function that recreates the integration test event dispatcher with a link to the applications container, so view lookups worked again:
```
export default function (context, app) {
  run(app, () => {
    // destroy the old dispatcher...
    context.dispatcher.destroy();

    // ... then replace it with a dispatcher that knows about the application container
    context.dispatcher = EventDispatcher.create({
      container: app.container
    });

    context.dispatcher.setup({}, '#ember-testing');
  });
}
```

In my tests I'd use it as such:
```
  beforeEach() {
    App = startApp();

    linkAppDispatcher(this, App);
  },
```

**Comment by rwjblue** [comment]
@praxxis - Thank you for the detailed explanation and workaround.

**Comment by praxxis** [comment]
Huzzah, I updated a bunch of dependencies (including going to Ember 2.0) and no longer need to re-link the container with the above workaround. I assume it was https://github.com/switchfly/ember-test-helpers/pull/92 that fixed it

**Comment by rwjblue** [comment]
FWIW, these helpers are available via `ember-native-dom-helpers`, and I plan to submit an RFC to expose them directly from ember-test-helpers in the near future (as soon as the changes from emberjs/rfcs#232 are totally finished).

I'm going to close this for now (since it is possible with that addon)...
