### ISSUE TITLE
Working with new Container/Registry Implementation

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember-test-helpers#7]
@dgeb - You are the most knowledgeable on these changes in Ember itself. What changes are needed here to accommodate them?

**Comment by rwjblue** [comment]
@dgeb - We really need to make a game plan for this, as 1.11.0-beta.1 will be shipping in a couple weeks....

**Comment by dgeb** [comment]
@rwjblue ok, so the game plan we discussed in IRC is:

1. Fix up `isolatedContainer` to avoid deprecations for now
  1. Build a registry with `Application.buildRegistry()` - eliminating need for custom registrations
  1. Create a container with `registry.container()`
  1. Override `container.register` to call `container._registry.register` without deprecations. Consider overriding other registry calls without deprecations as well.

1. Try to introduce a `Session` in Ember itself before branching to beta for 1.11
  1. ember-test-helpers can work with `Session` instead of `isolatedContainer`, if supported

**Comment by rwjblue** [comment]
Downstream issue in ember-qunit: https://github.com/rwjblue/ember-qunit/issues/118

**Comment by dgeb** [comment]
The deprecation warnings are now showing up in 1.11 beta, so we need to tackle this very soon.

**Comment by rwjblue** [comment]
Yes, agreed.

**Comment by dgeb** [comment]
See https://github.com/switchfly/ember-test-helpers/pull/15 for a quick fix to silence the deprecation warnings. I avoided the steps above (for now) because `buildRegistry` has gotten more complicated, and now involves configuration of a resolver. I think all that can wait until we straighten out `ApplicationInstance` and expose that for testing instead `isolatedContainer`.

**Comment by Turbo87** [comment]
It seems to me that this issue is no longer relevant 🤔
