### ISSUE TITLE
@ember/test-helpers@2 breaks build with mini-css-extract-plugin and ember-auto-import

### ISSUE THREAD

**Issue by andreyfel** [emberjs/ember-test-helpers#961]
We are using `mini-css-extract-plugin` and `ember-auto-import` to import styles from fullcalendar@5.
The config looks like this:
```
    autoImport: {
      webpack: {
        plugins: [
          new MiniCssExtractPlugin({
            filename: 'vendor.css',
          }),
        ],
        module: {
          rules: [{
            test: /\.css$/,
            use: [MiniCssExtractPlugin.loader, 'css-loader'],
          }],
        },
      },
    },
```
It became possible after this was added to ember-auto-import https://github.com/ef4/ember-auto-import/pull/205

It was working fine so far.

I was trying to update our app to ember-qunit@5 and @ember/test-helpers@2. After doing the migration I've started getting the error:
```
ERROR in ../node_modules/@fullcalendar/daygrid/main.css
Module build failed (from ../node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../node_modules/mini-css-extract-plugin/dist/loader.js):
Error: Didn't get a result from child compiler
...
```

If I remove `@ember/test-helpers` from the package.json the build starts working again. This is why I'm opening the issue against this repo, however, it might be something upstream.

**Comment by rwjblue** [comment]
Can you make a reproduction? It seems difficult to debug from the error message itself...

**Comment by andreyfel** [comment]
Here is the reproduction: https://github.com/andreyfel/mini-css-extract-plugin-with-ember-test-helpers-2-bug
The latest commit won't build.
If you rollback one commit back, it works.

**Comment by andreyfel** [comment]
@rwjblue I've tried to update all the dependencies to latest (ember-cli 3.23, ember-auto-import 1.10, etc.) but it didn't help.
See the latest commit in the reproduction repository.

**Comment by boris-petrov** [comment]
@rwjblue - we just hit this as well. We're not using `mini-css-extract-plugin`. Just `ember-auto-import` with `css-loader` and `style-loader`. It's blocking us from updating `ember-qunit` (and hence `@ember/test-helpers`).

**Comment by mfeckie** [comment]
Not exactly the same or a repro exactly, I've experience a similar problem.

https://github.com/ef4/ember-auto-import/issues/337#issuecomment-756541525 Explains what's happening.

It _appears_ that recent changes cause the parent app the be included twice by `ember-auto-import`.  If you have webpack config for `ember-auto-import`, this causes problems because it causes webpack to break

**Comment by andreyfel** [comment]
@rwjblue sorry to bother you, did you have a chance to look at this issue? It prevents us from upgrading to the latest versions of ember-qunit and test-helpers.

**Comment by rwjblue** [comment]
Sorry, I haven't had time to dig into it much yet. I still don't fully understand what is going on though, we aren't using any custom / special webpack config in ember-qunit we just rely on ember-auto-import to do its normal thing 🤔.

**Comment by mfeckie** [comment]
@rwjblue I found this information when I looked at what was happening

(from https://github.com/ef4/ember-auto-import/issues/337#issuecomment-756541525)
Running into the same problem when upgrading to ember-cli 3.24. 

Digging in a bit more, I found this

https://github.com/webpack/webpack/issues/10843 seemed to provide a bit of a clue.

And when I run ember with the debug flags for auto-import, I see this

`ember-auto-import:bundler extraWebpackConfig {"module":{"rules":[{"test":{},"use":["style-loader","css-loader"]},{"test":{},"use":["style-loader","css-loader"]}]}} +0ms`

So it looks like something is causing the rule to appear twice.

If I look through the process using node debugger,  I can see that my ember application ends up in the `Set` of packages `this.options.packages` twice.

As far as I can tell, the breakage happens on Ember-CLI 3.24, not on 3.23.

If I remove

```json
    "@ember/test-helpers": "2.0.0",
```

and pin `ember-qunit`

```json
-    "ember-qunit": "^5.1.1",
+    "ember-qunit": "4.6.0",
```

Then the problem goes away.

**Comment by boris-petrov** [comment]
@mfeckie - as I mentioned in the [other issue](https://github.com/ef4/ember-auto-import/issues/337#issuecomment-756863684), the problem is not in `ember-cli`. The same issue appears in both 3.23 and 3.24. The problem is somewhere in `@ember/test-helpers` and/or `ember-qunit`.

**Comment by mfeckie** [comment]
@boris-petrov I agree, my point was that I started seeing the problem when I upgraded to 3.24 because the blueprint uses `@ember/test-helpers and ember-qunit` versions where the problem seems to exist

**Comment by rwjblue** [comment]
Can y'all double check with `@ember/test-helpers@2.2.1` (published yesterday)?

**Comment by boris-petrov** [comment]
@rwjblue - at least for me, the problem is resolved. Thanks!

**Comment by andreyfel** [comment]
For some reason, it magically started working! Thanks, @rwjblue!

The only change in this version is this PR: https://github.com/emberjs/ember-test-helpers/pull/992

Was it because of es6-promise? (seems unrelated)

I noticed that `ember-auto-import` was moved from `dependencies` to `devDependencies`. Apparently, it fixed our issue here?

`ember-auto-import` docs say `ember-auto-import must be in the dependencies of your addon, not in devDependencies. Otherwise it won't come along when people install your addon.`.

It would be nice to understand the magic behind this change.

**Comment by rwjblue** [comment]
> I noticed that ember-auto-import was moved from dependencies to devDependencies. Apparently, it fixed our issue here?

Yes, that was what I suspected.

> ember-auto-import docs say ember-auto-import must be in the dependencies of your addon, not in devDependencies. Otherwise it won't come along when people install your addon.

These docs are correct, the change in #992 removed the need for us to have ember-auto-import when _consumed_. We only need ember-auto-import (after #992) to handle our own tests importing of `qunit`, that is why it is OK to be in `devDependencies` (which FWIW is how it is in the default new addon blueprint).

**Comment by andreyfel** [comment]
I'm wondering why `ember-auto-import` in dependencies was causing these issues? There are other addons in our app having it in the dependencies and they are not causing such issues.

**Comment by achambers** [comment]
Hi folks. I'm finding myself being bitten by the same errors/symptoms I'm seeing in this issue. However, upgrading @ember/test-helpers doesn't seem to be fixing things for me. My setup is ever so slightly different to above, however.

I didn't hit the error when upgrading to ember@3.24.0. My app is on 3.23.1. However, the version of ember-auto-import being used is 1.10.1 which seems to be the version that this error starts to manifest itself.

I have verified that I am also getting the duplicated rules in the ember-auto-import debug out (as per https://github.com/emberjs/ember-test-helpers/issues/961#issuecomment-762308138).

In order to try and update to the supposedly patched test helpers, I did the following:

1. yarn upgrade ember-qunit --latest
2. yarn add qunit @ember/test-helper -D

So, unless I misunderstand things, I believe I'm using the patched version of test-helpers that was supposed to fix this bug. However, I'm still experiencing it.

I have tried do document things here https://github.com/ef4/ember-auto-import/issues/372

Is anyone here able to give me a steer on how to get past this? Is there any reason why being on 3.23.0 could be a contributing factor here? And would getting to Ember 3.25.x fix this?
